export const WORDINGS = {
  app: {
    title: 'JSON Editor',
    untitled: 'Untitled',
  },
  menu: {
    file: 'File',
    edit: 'Edit',
    view: 'View',
    help: 'Help',
    new: 'New File',
    open: 'Open File',
    save: 'Save',
    saveAs: 'Save As',
    close: 'Close File',
    exit: 'Exit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    delete: 'Delete',
    selectAll: 'Select All',
    toggleTheme: 'Toggle Theme',
    toggleSidebar: 'Toggle Sidebar',
  },
  toolbar: {
    newFile: 'New',
    openFile: 'Open',
    saveFile: 'Save',
    saveAsFile: 'Save As',
    schema: 'Schema',
    validate: 'Validate',
    format: 'Format',
    addEntry: 'Add Entry',
    deleteEntry: 'Delete',
    undo: 'Undo',
    redo: 'Redo',
  },
  editor: {
    raw: 'Raw JSON',
    gui: 'Form Editor',
    placeholder: 'Enter JSON content here...',
    invalidJson: 'Invalid JSON',
    validJson: 'Valid JSON',
    noFile: 'No file opened',
    modified: 'Modified',
    saved: 'Saved',
  },
  schema: {
    title: 'JSON Schema',
    define: 'Define Schema',
    edit: 'Edit Schema',
    delete: 'Delete Schema',
    noSchema: 'No schema defined',
    addProperty: 'Add Property',
    removeProperty: 'Remove',
    required: 'Required',
    optional: 'Optional',
    type: 'Type',
    key: 'Key',
    defaultValue: 'Default Value',
    description: 'Description',
  },
  dialog: {
    save: {
      title: 'Save Changes',
      message: 'Do you want to save the changes to the current file?',
      save: 'Save',
      discard: 'Discard',
      cancel: 'Cancel',
    },
    schema: {
      title: 'Schema Editor',
      create: 'Create Schema',
      modify: 'Modify Schema',
      apply: 'Apply',
      cancel: 'Cancel',
    },
    addEntry: {
      title: 'Add New Entry',
      key: 'Key',
      value: 'Value',
      type: 'Type',
      add: 'Add',
      cancel: 'Cancel',
    },
  },
  contextMenu: {
    copy: 'Copy',
    cut: 'Cut',
    paste: 'Paste',
    delete: 'Delete',
    addNew: 'Add New',
    edit: 'Edit',
    collapse: 'Collapse All',
    expand: 'Expand All',
  },
  sidebar: {
    title: 'File Structure',
    noContent: 'No content to display',
    root: 'Root',
    array: 'Array',
    object: 'Object',
  },
  validation: {
    required: 'This field is required',
    typeError: 'Type mismatch',
    minimum: 'Value is below minimum',
    maximum: 'Value exceeds maximum',
    minLength: 'String is too short',
    maxLength: 'String is too long',
    pattern: 'Pattern mismatch',
    enum: 'Value not in allowed list',
  },
  status: {
    ready: 'Ready',
    loading: 'Loading...',
    error: 'Error',
    saved: 'Saved successfully',
  },
  os: {
    mac: {
      save: 'Cmd+S',
      open: 'Cmd+O',
      new: 'Cmd+N',
    },
    default: {
      save: 'Ctrl+S',
      open: 'Ctrl+O',
      new: 'Ctrl+N',
    },
  },
} as const;

export type Wordings = typeof WORDINGS;